Nydus: fix panic on layer umount
If some error occurs in `mountWithLower`, will cause that panic
on umount in defer function:

```
panic: close of nil channel
    pkg/driver/nydus/packer.(*BuildLayer).umount(...)
    pkg/driver/nydus/packer/layer.go:93
```

Fix it by checking nil channel, the root cause is an error be
returned from GetOverlayLayers:

```
error: unknown option redirect_dir specified by snapshotter.
```

Fix it by updating ported code.

Signed-off-by: Yan Song <imeoer@linux.alibaba.com>